/**********************************************************************************************************************
 * \file DMA_ADC_Transfer.h
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

#ifndef DMA_ADC_TRANSFER_H_
#define DMA_ADC_TRANSFER_H_

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "Ifx_Types.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
/* ASCLIN Macros */
#define ISR_PRIORITY_ASCLIN_TX  1           /* Priority for interrupt ISR Transmit                                  */
#define ISR_PRIORITY_ASCLIN_RX  2           /* Priority for interrupt ISR Receive                                   */
#define ISR_PRIORITY_ASCLIN_ER  3           /* Priority for interrupt ISR Errors                                    */
#define ASC_TX_BUFFER_SIZE      64          /* Transmission buffer size                                             */
#define ASC_RX_BUFFER_SIZE      64          /* Reception buffer size                                                */
#define ASC_PRESCALER           1           /* Division ratio of the predivider for ASCLIN clock                    */
#define ASC_BAUDRATE            115200      /* Baudrate of the serial communication                                 */

#define RX_LENGTH               1           /* RX message length                                                    */
#define PASS_CHARACTER          '1'         /* Character which enables the ADC conversion + DMA transfer            */
#define RESET_CHARACTER         '0'         /* Reset value of UART exchange character after a DMA transfer          */
#define ACK_TEXT_LENGTH         11          /* Length of the acknowledgment message after a DMA transfer            */
#define COMPLETED_TRANSFER_TEXT "Rajkanna!\r\n"    /* Text to write as feedback for the user when a DMA
                                                         * transfer is finished                                     */

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/
void init_UART(void);
void receive_data(char *data, Ifx_SizeT length);
void send_data(char *data, Ifx_SizeT length);

#endif /* DMA_ADC_TRANSFER_H_ */
